/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOSSAM
 */
public class categories extends javax.swing.JFrame {

    /**
     * Creates new form categories
     */
    public categories() {
        initComponents(); 
        read();
    }

    public void read() {
        try {
            int i = 0;
            File myObj = new File("cat.txt");
            Scanner myReader = new Scanner(myObj);
            while (myReader.hasNextLine()) {

                DefaultTableModel model = (DefaultTableModel) table.getModel();
                String data = myReader.nextLine();
               
                //System.out.println(data);
                
                String[] d = data.split("\t", 0);
                model.insertRow(i, d);
                i++;

            }
            myReader.close();
        } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        catid = new javax.swing.JTextField();
        lable2 = new javax.swing.JLabel();
        lable1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        catname = new javax.swing.JTextField();
        ubdate = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setForeground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(204, 204, 204));
        add.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add.setText("ADD");
        add.setBorder(new javax.swing.border.MatteBorder(null));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 141, 150, 40));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ));
        table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 406, 290));

        jButton5.setBackground(new java.awt.Color(0, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton5.setText("Home ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 430, 36));
        jPanel1.add(catid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 150, -1));

        lable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lable2.setText("ID");
        jPanel1.add(lable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        lable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lable1.setText("Name");
        jPanel1.add(lable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 41));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("categorise");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 210, 60));

        catname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catnameActionPerformed(evt);
            }
        });
        jPanel1.add(catname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 150, -1));

        ubdate.setBackground(new java.awt.Color(204, 204, 204));
        ubdate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ubdate.setText("update");
        ubdate.setBorder(new javax.swing.border.MatteBorder(null));
        ubdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubdateActionPerformed(evt);
            }
        });
        jPanel1.add(ubdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 211, 150, 40));

        delete.setBackground(new java.awt.Color(204, 204, 204));
        delete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delete.setText("delete");
        delete.setBorder(new javax.swing.border.MatteBorder(null));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 281, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String name = catname.getText();
        int id = Integer.parseInt(catid.getText());
        try {
            FileWriter myWriter = new FileWriter("cat.txt", true);
            myWriter.write(id + "\t");
            myWriter.write(name + "\t");
            myWriter.write("\n");
            myWriter.close();
            System.out.println("Successfully wrote to the file.");
        } catch (IOException ex) {
            Logger.getLogger(Add_offer.class.getName()).log(Level.SEVERE, null, ex);
        }
        categoriesMenu m =new categoriesMenu();
        m.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_addActionPerformed

    private void ubdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubdateActionPerformed
        // TODO add your handling code here:
        //Change names of varuables
        String name = catname.getText();
        int id= Integer.parseInt(catid.getText());
        try {
            int n = 0 ;
            String[] arr = new String[100] ;
            File myObj = new File("cat.txt");
            Scanner myReader = new Scanner(myObj);
            while (myReader.hasNextLine()) {
                String data = myReader.nextLine();
                //Cood here --> "Hazem"
                if(n==id-1)
                    arr[n]=(id + "\t" + name);
                else
                    arr[n] = data;
                n++;   
            }            
            myReader.close();
            FileWriter Writer = new FileWriter("tmep.txt",true);
            for (int j = 0;; j++) {
               if(arr[j]==null)
                     break;
               Writer.write(arr[j]+"\n");
            }           
            Writer.close();
            FileWriter myWriter = new FileWriter("cat.txt");
            myWriter.write("");
            myWriter.close();
            System.out.println("Successfully wrote to the file.");
            } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
           }catch (IOException ex) {
            Logger.getLogger(Add_offer.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("step 1");
        try {
            int n = 0 ;
            String[] arr = new String[100] ;
            File myObj = new File("tmep.txt");
            Scanner myReader = new Scanner(myObj);
            while (myReader.hasNextLine()) {
                String data = myReader.nextLine();              
                arr[n] = data;
                n++;   
            }          
            myReader.close();
            FileWriter Writer = new FileWriter("cat.txt",true);
            for (int j = 0;; j++) {
               if(arr[j]==null)
                     break;
               Writer.write(arr[j]+"\n");
            }           
            Writer.close();
            FileWriter myWriter = new FileWriter("tmep.txt");
            myWriter.write("");
            myWriter.close();
            System.out.println("Successfully wrote to the file.");
            }catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            }catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "user name or password wrong . ", "ERROR",JOptionPane.ERROR_MESSAGE);
        }
        categoriesMenu m =new categoriesMenu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_ubdateActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        
        try {
            FileWriter myWriter; myWriter = new FileWriter("cat.txt");
            myWriter.write("");
            myWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(categories.class.getName()).log(Level.SEVERE, null, ex);
        }
        categoriesMenu m =new categoriesMenu();
        m.setVisible(true);
        dispose();       
        
    }//GEN-LAST:event_deleteActionPerformed
    
    private void catnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catnameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_catnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new categories().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField catid;
    private javax.swing.JTextField catname;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lable1;
    private javax.swing.JLabel lable2;
    private javax.swing.JTable table;
    private javax.swing.JButton ubdate;
    // End of variables declaration//GEN-END:variables
}
